version: '3.1'

services:

  data_collector:
    build:
        context: .
        dockerfile: data_collector.Dockerfile
    tty: true
  
  censorship_analytics:
    build:
        context: .
        dockerfile: censorship_analytics.Dockerfile
    tty: true
