version: "2"

services:
  geth:
    image: ethereum/client-go:stable
    container_name: geth
    restart: unless-stopped
    #network_mode: host
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - type : bind
        source : /media/Warehouse/Warehouse/Ethereum/data
        target : /root
    command:
      - --ws
      - --ws.addr=0.0.0.0
      - --http
      - --http.addr=0.0.0.0
#     - --http.corsdomain=[read below]
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*

  lighthouse:
    image: sigp/lighthouse:latest-modern
    container_name: lighthouse
    restart: unless-stopped
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "127.0.0.1:5052:5052"
    volumes:
      - type : bind
        source : /media/Warehouse/Warehouse/Ethereum/lighthouse
        target : /root/.lighthouse
      - type : bind
        source : /media/Warehouse/Warehouse/Ethereum/data
        target : /geth/
        read_only: true
    command:
      - lighthouse
      - --network=mainnet
      - beacon
      - --http
      - --http-address=0.0.0.0
      - --execution-endpoint=http://geth:8551
      - --execution-jwt=/geth/.ethereum/geth/jwtsecret
      - --checkpoint-sync-url=https://beaconstate.info/
