global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: "app"

rule_files:

scrape_configs:
  - job_name: "app"

    static_configs:
      - targets: ["127.0.0.1:8000"]
